src/wml/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
from workorder.views import Home


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include("auth.urls")),
    url(r'^', include("workorder.urls")),
    url(r'^$', Home, name="home"),
]




if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

src/workorder/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import pre_save, post_save
from datetime import datetime, timedelta
# Create your models here.
import inspect

def current_user():
	for frame_record in inspect.stack():
		if frame_record[3]=='get_response':
			request = frame_record[0].f_locals['request']
			break
		else:
			request = None
	return request.user

JOB_STATUS = (
	("In Progress","In Progress"),
	("Quoting","Quoting"),
	("New Job","New Job"),
	("Completed","Completed"),
	("Invoicing","Invoicing"),
	("Closed","Closed")
	)

TASK_STATUS = (
	("Not Started","Not Started"),
	("Waiting for Parts","Waiting for Parts"),
	("Waiting for Labour","Waiting for Labour"),
	("Completed","Completed"),
	("In Progress","In Progress"),
	("On-Hold","On-Hold")
	)

PO_STATUS = (
	("Closed","Closed"),
	("New","New"),
	("Order Sent","Order Sent"),
	("Waiting Receipts","Waiting Receipts"),
	("Fully Receipted","Fully Receipted")
	)

INVOICE_STATUS = (
	("Sent","Sent"),
	("Paid","Paid")
	)


class Customer(models.Model):
	customer_name 	  = models.CharField(max_length = 100)
	customer_abn 	  = models.CharField(max_length=100)
	customer_contact  = models.CharField(max_length = 50)
	customer_email 	  = models.EmailField(max_length=254)
	customer_address  = models.TextField()
	customer_number   = models.CharField(max_length = 200)
	customer_contact1 = models.CharField(max_length = 200)
	customer_address1 = models.TextField()
	customer_number1  = models.CharField(max_length = 200)
	is_vendor		  = models.BooleanField(default = False)

	def __str__(self):
		return self.customer_name



class WorkOrder(models.Model):
	customer 				= models.ForeignKey(Customer,on_delete=models.CASCADE)
	description 			= models.TextField()
	description_long_text 	= models.TextField()
	initial_deu_date 		= models.DateField(null=True,blank=True)
	quote 					= models.PositiveIntegerField()
	customer_contact_date 	= models.DateField()
	quote_sent_date 		= models.DateField()
	revision 				= models.PositiveIntegerField()
	promised_delivery_date  = models.DateField()
	created_by 				= models.ForeignKey(User,on_delete=models.CASCADE,related_name='created_by',null=True,blank=True)
	created_date 			= models.DateTimeField(auto_now = True,auto_now_add = False)
	modified_by 			= models.ForeignKey(User,on_delete=models.CASCADE,related_name='modified_by',null=True,blank=True)
	modified_date 			= models.DateTimeField(auto_now = False,auto_now_add = True)
	job_status 				= models.CharField(max_length=100, choices=JOB_STATUS, default="Quoting")
	all_tasks_complete 		= models.BooleanField(default = False)
	is_template 			= models.BooleanField(default = False)


	def __str__(self):
		return self.description



DOC_CAT = (
	("Cat 1","Cat 1"),
	("Cat 2","Cat 2"),
	("Cat 3","Cat 3"),
	("Cat 4","Cat 4"),
	)


class Documentation(models.Model):
	work_order = models.ForeignKey(WorkOrder,on_delete=models.CASCADE)
	category = models.CharField(max_length=100, choices=DOC_CAT)	
	document   = models.FileField(upload_to = "documentation")

	def __str__(self):
		return "%s"%(self.id)


class Employee(models.Model):
	user                           = models.OneToOneField(User,null=True,blank=True)
	external_system 			   = models.PositiveIntegerField()
	name  						   = models.CharField(max_length=100)
	start_date 					   = models.DateField()
	terminate_date 				   = models.DateField(null=True,blank=True)
	terminated 					   = models.BooleanField(default=False)
	photo 						   = models.ImageField(upload_to="employee")
	address 					   = models.TextField()
	phone_number 				   = models.CharField(max_length = 50)
	emergency_contact 			   = models.CharField(max_length = 50)
	emergency_contact_relationship = models.CharField(max_length = 50)
	emergency_contact_number 	   = models.CharField(max_length = 50)
	cost_rate 					   = models.FloatField()
	chargeout_rate 				   = models.FloatField()

	def __str__(self):
		return self.name


def terminated_receiver(sender, instance, *args, **kwargs):
	if instance.terminate_date:
		instance.terminated = True
	else:
		instance.terminated = False

pre_save.connect(terminated_receiver, sender=Employee)


class Task(models.Model):
	work_order 		 = models.ForeignKey(WorkOrder,on_delete=models.CASCADE)
	task_description = models.TextField()
	start_date       = models.DateField()
	end_date         = models.DateField()
	task_status 	 = models.CharField(max_length=100, choices=TASK_STATUS, default="In Progress")
	task_duration 	 = models.IntegerField(default=0)
	task_assigned_to = models.ManyToManyField(Employee)
	task_due_date 	 = models.DateField()

	def __str__(self):
		return self.task_description

def task_duration_receiver(sender, instance, *args, **kwargs):
    day_between = instance.end_date-instance.start_date
    passed_hour = day_between.days * 24 + day_between.seconds // 3600
    instance.task_duration = int(passed_hour)

pre_save.connect(task_duration_receiver, sender=Task)


class TimeCard(models.Model):
	work_order 	  = models.ForeignKey(WorkOrder,on_delete=models.CASCADE)
	employee_name = models.ForeignKey(Employee,on_delete=models.CASCADE)
	start_time 	  = models.DateTimeField()
	end_time      = models.DateTimeField()
	duration      = models.FloatField(default=0)
	approved      = models.BooleanField(default = False)
	approved_date = models.DateTimeField(null=True,blank=True)

	gst = models.FloatField(default=0)
	total_cost = models.FloatField(default=0)
	mp = models.FloatField(default=0)
	ma = models.FloatField(default=0)

	def __str__(self):
		return self.employee_name.name

	def get_total_ex_gst(self):
		duration = self.duration
		chargeout_rate = self.employee_name.chargeout_rate
		markup_percentage = self.mp
		markup_amount = self.ma
		line_total_ex_gst = duration * chargeout_rate * (1+markup_percentage/100) + markup_amount
		return line_total_ex_gst

class Purchase(models.Model):
	work_order 				= models.ForeignKey(WorkOrder,on_delete=models.CASCADE)
	po_status 			  	= models.CharField(max_length=100, choices=PO_STATUS, default="New")
	vendor					= models.ForeignKey(Customer,on_delete=models.CASCADE)
	po_cost 				= models.FloatField(default=0)
	ordered_date 		 	= models.DateField(auto_now = True,auto_now_add = False)
	required_date 		 	= models.DateField()
	promised_delivery_date	= models.DateField()
	approved 			  	= models.BooleanField(default=False)

	def __str__(self):
		return self.work_order.description




class Item(models.Model):
	purchase 	= models.ForeignKey(Purchase,on_delete=models.CASCADE)
	line_text = models.CharField(max_length=200)
	quantity = models.PositiveIntegerField(default=1)
	received_qty = models.PositiveIntegerField(default=1)
	received_date = models.DateField()
	po_cost_ex_gst = models.FloatField(default=0)
	gst = models.FloatField(default=0)
	line_cost 	= models.FloatField(default=0)
	approved = models.BooleanField(default=False)
	mp = models.FloatField(default=0)
	ma = models.FloatField(default=0)
	is_markuped = models.BooleanField(default=False)

	def __str__(self):
		return self.line_text

	def get_total_ex_gst(self):
		qty = self.quantity
		cost = self.po_cost_ex_gst
		markup_percentage = self.mp
		markup_amount = self.ma
		line_total_ex_gst = qty * cost * (1+markup_percentage/100) + markup_amount
		return line_total_ex_gst




class Invoice(models.Model):
	work_order						= models.OneToOneField(WorkOrder,on_delete=models.CASCADE)
	external_account_code 			= models.CharField(max_length=100,null=True, blank=True)
	invoice_date 					= models.DateField(null=True, blank=True)
	expected_payment_date 			= models.DateField(null=True, blank=True)
	invoice_status 					= models.CharField(max_length=100, choices=INVOICE_STATUS,null=True, blank=True)
	email_to 						= models.EmailField(max_length = 100,null=True, blank=True)
	description 					= models.TextField(null=True, blank=True)
	payment_details 				= models.TextField(null=True, blank=True)
	invoice_to 						= models.TextField(null=True, blank=True)
	invoice_from_org 				= models.TextField(null=True, blank=True)
	invoice_from 					= models.TextField(null=True, blank=True)
	invoice_customer 				= models.ForeignKey(Customer, on_delete=models.CASCADE, null=True, blank=True)
	invoice_customer_info 			= models.TextField(null=True, blank=True)
	is_created                      = models.BooleanField(default=False)
	send_copy_tick_box 				= models.BooleanField(default = False)
	add_pdf_attachment_tick_box 	= models.BooleanField(default = False)
	add_invoice_attachment_to_email = models.BooleanField(default = False)
	approved                        = models.BooleanField(default=False)
	
	def __str__(self):
		return self.work_order.description

to_form = '''
{}
{}
'''

def invoice_create_receiver(sender, instance, created, *args, **kwargs):
	if created:
		ito = to_form.format(instance.customer.customer_name, instance.customer.customer_address).strip()
		icf = to_form.format(instance.customer.customer_name, instance.customer.customer_email).strip()
		Invoice.objects.create(
			work_order = instance,
			email_to = instance.customer.customer_email,
			invoice_customer = instance.customer,
			invoice_to = ito,
			invoice_customer_info = icf
			)

post_save.connect(invoice_create_receiver, sender=WorkOrder)

def deu_date_receiver(sender, instance, *args, **kwargs):
	if instance.job_status == "Quoting" or instance.job_status == "New Job":
		pdd = instance.promised_delivery_date
		instance.initial_deu_date = pdd
pre_save.connect(deu_date_receiver, sender=WorkOrder)


class Preference(models.Model):
	user = models.OneToOneField(User)
	logo = models.ImageField(upload_to="invoice_logo", null=True,blank=True)
	address = models.TextField(null=True,blank=True)
	markup_percentage = models.FloatField(default=0)
	markup_amount = models.FloatField(default=0)

	def __str__(self):
		return self.user.username


def preference_receiver(sender,created, instance, *args, **kwargs):
	if created:
		Preference.objects.create(
			user = instance

src/templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    
    <title>Work Management Lite Application</title>
  

{% include 'css.html' %}

  <style>
    .xactive{
      background-color: #3e8ef71a !important;
    }
    textarea {
      resize: none;
    }

  input[type="number"] {
    -webkit-appearance: textfield;
       -moz-appearance: textfield;
            appearance: textfield;
  }
  input[type=number]::-webkit-inner-spin-button, 
  input[type=number]::-webkit-outer-spin-button { 
    -webkit-appearance: none;
  }

  .top10{
    margin-top: 10px;
  }

  .right10{
    margin-right: 10px;
  }

  .form-group {
      margin-bottom: 0 !important;;
  }

  label {
      margin-bottom: 0;
      margin-top: 8px;
  }

  .add-row{
    margin: 10px !important;
  }
.modal {
  overflow-y:auto;
}



  </style>

</head>

<body class="hold-transition skin-info dark-sidebar sidebar-mini dark">
<div class="wrapper">
{% include 'header.html' %}
{% include 'sidebar.html' %}
  
  <div class="content-wrapper">
	  <div class="container">

		{% block content %}
		{% endblock %}

	  </div>
  </div>
 
   <footer class="main-footer">
	  &copy; 2018 <a href="">Company Name</a>. All Rights Reserved.
  </footer>
</div>

{% include 'js.html' %}
{% block js %}{% endblock %}
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.formset/1.2.2/jquery.formset.min.js"></script>
	
</body>
</html>

src/templates/css.html
	{% load staticfiles %}


	<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
	
	<!-- Data Table-->
	<link rel="stylesheet" type="text/css" href="{% static 'css/datatables.min.css' %}"/>
	
	<!-- Bootstrap extend-->
	<link rel="stylesheet" href="{% static 'css/bootstrap-extend.css' %}">

	<!-- Theme style -->
	<link rel="stylesheet" href="{% static 'css/master_style.css' %}">

	<!-- UltimatePro Admin skins -->
	<link rel="stylesheet" href="{% static 'css/_all-skins.css' %}">
	<link rel="stylesheet" href="{% static 'css/bootstrap-datetimepicker.css' %}">

	<link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">

src/templates/header.html
{% load staticfiles %}

  <header class="main-header">
    <!-- Logo -->
    <a href="" class="logo">
      <!-- mini logo -->
	  <div class="logo-mini">
		  <span class="light-logo"><img src="{% static 'img/logo.png' %}" alt="logo" style="width: 70%;"></span>
	  </div>
    </a>
    <!-- Header Navbar -->
    <nav class="navbar navbar-static-top">
      <!-- Sidebar toggle button-->
	  <div>
		  <a href="#" class="sidebar-toggle" data-toggle="push-menu" role="button">
			<i class="fa fa-align-left"></i>
		  </a>		
	  </div>
		
      <div class="navbar-custom-menu r-side">
        <ul class="nav navbar-nav">
		  <!-- Messages -->
		  <!-- Notifications -->
		  <!-- Tasks-->
		  <!-- User Account-->
          <li class="dropdown user user-menu">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <img src="{% static 'img/1.jpg' %}" class="user-image rounded-circle" alt="User Image">
            </a>
            <ul class="dropdown-menu animated flipInX">
              <!-- User image -->
              <li class="user-header bg-img" style="background-image: url({% static 'img/user-info.jpg' %})" data-overlay="3">
				  <div class="flexbox align-self-center">					  
				  	<img src="{% static 'img/1.jpg' %}" class="float-left rounded-circle" alt="User Image">					  
					<h4 class="user-name align-self-center">
					  <span>{% if request.user.first_name %}{{ request.user.first_name }}{% else %} {{ request.user }} {% endif %}</span>
					  <small>{{ request.user.email }}</small>
					</h4>
				  </div>
              </li>
              <!-- Menu Body -->
              <li class="user-body">
            <a class="dropdown-item" href="{% url 'change_password' %}"><i class="fa fa-key"></i> Change Password</a>
				    <a class="dropdown-item" href="{% url 'preference_update' request.user.preference.id %}"><i class="fa fa-cog"></i> Preference</a>
					<a class="dropdown-item" href="{% url 'logout' %}"><i class="fa fa-power-off"></i> Logout</a>
					<div class="dropdown-divider"></div>
					<div class="p-10"><a href="{% url 'user_details' request.user.id %}" class="btn btn-sm btn-rounded btn-success">View Profile</a></div>
              </li>
            </ul>
          </li>	
			
		  
          <!-- Control Sidebar Toggle Button -->
			
        </ul>
      </div>
    </nav>
  </header>

src/templates/home.html
{% extends 'base.html' %}
{% load widget_tweaks %}


{% block content %}

{% if perms.workorder.add_workorder %}
          <h1>add</h1>
{% endif %}

{% if perms.workorder.change_workorder %}
          <h1>change</h1>
{% endif %}

		<div class="content-header">
			<div class="d-flex align-items-center">
				<div class="mr-auto">
					<h3 class="page-title">Work Order List</h3>
					<div class="d-inline-block align-items-center">
						<nav>
							<ol class="breadcrumb">
								<li class="breadcrumb-item"><a href="#"><i class="fa fa-home"></i></a></li>
								<li class="breadcrumb-item" aria-current="page">Work Order</li>
								<li class="breadcrumb-item active" aria-current="page">Work Order List</li>
							</ol>
						</nav>
					</div>
				</div>
				<div class="right-title">
				</div>
			</div>
		</div>


<section class="content">

		  <div class="row">
			<div class="col-xl-4 col-md-6 col-12 ">
				<div class="box box-inverse box-success">
				  <div class="box-body">
					<div class="flexbox">
					  
					</div>

					<div class="text-center my-2">
					  <div class="font-size-60">{{ open_order }}</div>
					  <span>Open Work Orders</span>
					</div>
				  </div>
				</div>
			</div>
			<!-- /.col -->
			<div class="col-xl-4 col-md-6 col-12 ">
				<div class="box box-inverse box-primary">
				  <div class="box-body">
					<div class="flexbox">
					  
					</div>

					<div class="text-center my-2">
					  <div class="font-size-60">{{ deu_date }}</div>
					  <span>Work Orders Due This week</span>
					</div>
				  </div>				
				</div>
			</div>
			<!-- /.col -->

			<div class="col-xl-4 col-md-6 col-12">
				<div class="box box-inverse box-danger">
				  <div class="box-body">
					<div class="flexbox">
					  
					</div>

					<div class="text-center my-2">
					  <div class="font-size-60">{{ overdeu_date }}</div>
					  <span>Work Orders Overdue</span>
					</div>
				  </div>

				</div>
			</div>
			<!-- /.col -->
<!-- 			<div class="col-xl-3 col-md-6 col-12">
				<div class="box box-inverse box-warning">
				  <div class="box-body">
					<div class="flexbox">
					  <h5>Pending Invoice</h5>
					</div>

					<div class="text-center my-2">
					  <div class="font-size-60">00</div>
					  <span>Pending</span>
					</div>
				  </div>
				</div>
			</div> -->
			<!-- /.col -->

		  </div>	

		  <div class="row">
				<div class="col-12">
					<div class="box">
						<div class="box-header with-border">
						<div class="pull-right">
							<a data-toggle="modal" data-target="#myModal" href="#"><i class="fa fa-plus-square-o fa-2x" aria-hidden="true"></i></a>
						</div>		
							<h4 class="box-title">Work Order List</h4>
							<h6 class="box-subtitle">Export Work Order List to Copy, CSV, Excel, PDF & Print</h6>
						</div>
						<div class="box-body">						
							<div class="table-responsive">
								
								<table id="example" class="table table-lg invoice-archive">
									<thead>
										<tr>
											<th>#</th>
											<th>Description</th>
											<th>Quote sent date</th>
											<th>Job status</th>
											<th>Customer contact date</th>
											<th>Initial deu date</th>
											<th>Quote</th>
											<th class="text-center">Actions</th>
										</tr>
									</thead>
									<tbody>

									{% for workorder in workorders %}
										<tr>
											<td>#{{ workorder.id }}</td>
											<td>{{ workorder.description }}</td>
											<td> {{ workorder.quote_sent_date|date:"D d/m/y" }}	</td>
									
											<td>{{ workorder.job_status }}</td>
											<td>
												{{ workorder.customer_contact_date|date:"D d/m/y" }}
											</td>
											<td>
												<span class="badge badge-success"> {{ workorder.initial_deu_date }}</span>
											</td>
											<td>
												<h6 class="mb-0 font-weight-bold">
												{{ workorder.quote }} </h6>
											</td>
											<td class="text-center">
												<div class="list-icons d-inline-flex">
													<div class="list-icons-item dropdown">
														<a href="#" class="list-icons-item dropdown-toggle" data-toggle="dropdown"><i class="fa fa-file-text"></i></a>
														<div class="dropdown-menu dropdown-menu-right">
															<a href="#" class="dropdown-item" id="workorder_edit" data-url = "{% url 'workorder_update' workorder.id %}" >
																<i class="fa fa-pencil"></i> Edit</a>
															<a href="{% url 'workorder_delete' workorder.id %}" class="dropdown-item"><i class="fa fa-remove"></i> Remove</a>
														</div>
													</div>
												</div>
											</td>
										</tr>

										{% endfor %}



									</tbody>
								</table>
																
							</div>
						</div>
					</div>
				</div>
			</div>
		  <!-- /.row -->

		</section>


<div class="modal fade" id="myModal">
    <div class="modal-dialog modal-lg">
      <div class="modal-content">
      
        <!-- Modal Header -->
        <div class="modal-header">
          <h4 class="modal-title">Create Work Order</h4>
          <button type="button" class="close" data-dismiss="modal">&times;</button>
        </div>
        
        <!-- Modal body -->
        <div class="modal-body">
              <div class="form-group">


      <form action="{% url 'workorder_create' %}" method="POST">{% csrf_token %}

<div class="row">
	<div class="col-sm-6">
		<div class="form-group">
      	<label>Customer:</label>
        {% render_field work_form.customer class="form-control" %}
    </div>
 </div>

<div class="col-sm-6">
	 <div class="form-group">
      	<label>Description:</label>
        {% render_field work_form.description class="form-control" rows="1" %}
      </div>
</div>

</div>

<div class="row">
	<div class="col-sm-6">
	<div class="form-group">
      	<label>Long Description:</label>
        {% render_field work_form.description_long_text class="form-control" rows="1" %}
      </div>
  </div>
      <div class="col-sm-6">
      	<div class="form-group">
      	<label>Quote:</label>
        {% render_field work_form.quote class="form-control"  %}
      </div>
		
	</div>
	
</div>


<div class="row">
	<div class="col-sm-6">
      <div class="form-group">
      	<label>Customer Contact Date:</label>
        {% render_field work_form.customer_contact_date class="form-control" %}
      </div>		
	</div>
<div class="col-sm-6">
       <div class="form-group">
       	<label>Quote Sent Date:</label>
        {% render_field work_form.quote_sent_date class="form-control" %}
      </div>	
</div>
</div>


<div class="row">
	<div class="col-sm-6">
 		<div class="form-group">
 		 <label>Revision:</label>
        {% render_field work_form.revision class="form-control" %}
      </div>
    </div>

<div class="col-sm-6">
      <div class="form-group">
      	<label>Promised Delivery Date:</label>
        {% render_field work_form.promised_delivery_date class="form-control" %}
      </div>	
</div>


	
</div>


<div class="row">
	<div class="col-sm-6">
      <div class="form-group">
      	<label>Job Status:</label>
        {% render_field work_form.job_status class="form-control" %}
      </div>
		
	</div>
</div>





<p class="top10">
	<button type="submit" class="btn btn-primary pull-right">Submit</button>
	<button type="button" class="btn btn-danger pull-right right10" data-dismiss="modal">Close</button>
</p>

      </form>

    </div>
        </div>
        

      </div>
    </div>
  </div>

  <div id="editcontainer"></div>

{% endblock %}

src/templates/js.html
	{% load staticfiles %}
	<script src="{% static 'js/jquery-3.3.1.js' %}"></script>
	<script src="{% static 'js/popper.min.js' %}"></script>
	<script src="{% static 'js/bootstrap.min.js' %}"></script>
	
    <script src="{% static 'js/datatables.min.js' %}"></script>
	<script src="{% static 'js/jquery.slimscroll.min.js' %}"></script>

	<script src="{% static 'js/template.js' %}"></script>
	<script src="{% static 'js/data-table.js' %}"></script>

	<script src="{% static 'js/index.js' %}"></script>
	
	<script src="{% static 'js/bootstrap-datetimepicker.js' %}"></script>

src/templates/preference.html
{% extends 'base.html' %}
{% load widget_tweaks %}
{% block content %}

<div class="content-header">
	<div class="d-flex align-items-center">
		<div class="mr-auto">
			<h3 class="page-title">Update Preference</h3>
			<div class="d-inline-block align-items-center">
				<nav>
					<ol class="breadcrumb">
						<li class="breadcrumb-item"><a href="#"><i class="fa fa-home"></i></a></li>
						<li class="breadcrumb-item" aria-current="page">preference</li>
						<li class="breadcrumb-item active" aria-current="page">preference update
						</li>
					</ol>
				</nav>
			</div>
		</div>
		<div class="right-title">
		</div>
	</div>
</div>

<div class="col-sm-12">
<form method="post" action="" enctype="multipart/form-data">{% csrf_token %}
 <div class="row">
  <div class="col-sm-6">
    <div class="form-group">
          <label>Address:</label>
          {% render_field form.address class="form-control" rows="1" %}
      </div>
  </div>

  <div class="col-sm-6">
     <div class="form-group">
          <label>Logo:</label>
          {% render_field form.logo class="form-control" %}
        </div>
  </div>
</div>

 <div class="row">
  <div class="col-sm-6">
    <div class="form-group">
          <label>Markup Percentage:</label>
          {% render_field form.markup_percentage class="form-control" %}
      </div>
  </div>

  <div class="col-sm-6">
     <div class="form-group">
          <label>Markup Amount:</label>
          {% render_field form.markup_amount class="form-control" %}
        </div>
  </div>
</div>

<p class="top10">
<button type="submit" class="btn btn-primary pull-right">Save</button>
</p>

</form>
</div>


{% endblock %}

src/templates/sidebar.html
  <aside class="main-sidebar">
    <!-- sidebar-->
    <section class="sidebar">
      
      <!-- sidebar menu-->
      <ul class="sidebar-menu" data-widget="tree">
		  
	
       <li>
          <a href="{% url 'home' %}" id="id_workorder">
            <i class="mdi mdi-wrench"></i>
              <span>Work Order</span>
          </a>
        </li> 


		   <li>
          <a href="{% url 'employee_list' %}" id="id_employee">
            <i class="mdi mdi-contact-mail"></i>
              <span>Employee</span>
          </a>
        </li> 

          <li>
          <a href="{% url 'customer_list' %}" id="id_customer">
            <i class="mdi mdi-human-male"></i>
      <span>Customer</span>
          </a>
        </li> 

		  <li>
          <a href="{% url 'purchase_list' %}" id="id_purchase">
            <i class="mdi mdi-cart-outline"></i>
			<span>Purchase</span>
          </a>
        </li> 
        
          <li>
          <a href="{% url 'timecard_list' %}" id="id_timecard">
            <i class="mdi mdi-clock"></i>
              <span>Time card</span>
          </a>
        </li> 



          <li>
          <a href="{% url 'documentation_list' %}" id="id_documentation">
            <i class="mdi mdi-paperclip"></i>
            <span>Documentation</span>
          </a>
        </li> 


          <li>
          <a href="{% url 'invoice_list' %}" id="id_invoice">
            <i class="mdi mdi-credit-card-multiple"></i>
            <span>Invoice</span>
          </a>
        </li> 


      </ul>
    </section>
  </aside>
  