src/wml/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
from workorder.views import Home


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include("auth.urls")),
    url(r'^', include("workorder.urls")),
    url(r'^$', Home, name="home"),
]




if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

src/workorder/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import pre_save, post_save
from datetime import datetime, timedelta
# Create your models here.
import inspect

def current_user():
	for frame_record in inspect.stack():
		if frame_record[3]=='get_response':
			request = frame_record[0].f_locals['request']
			break
		else:
			request = None
	return request.user

JOB_STATUS = (
	("In Progress","In Progress"),
	("Quoting","Quoting"),
	("New Job","New Job"),
	("Completed","Completed"),
	("Invoicing","Invoicing"),
	("Closed","Closed")
	)

TASK_STATUS = (
	("Not Started","Not Started"),
	("Waiting for Parts","Waiting for Parts"),
	("Waiting for Labour","Waiting for Labour"),
	("Completed","Completed"),
	("In Progress","In Progress"),
	("On-Hold","On-Hold")
	)

PO_STATUS = (
	("Closed","Closed"),
	("New","New"),
	("Order Sent","Order Sent"),
	("Waiting Receipts","Waiting Receipts"),
	("Fully Receipted","Fully Receipted")
	)

INVOICE_STATUS = (
	("Sent","Sent"),
	("Paid","Paid")
	)


class Customer(models.Model):
	customer_name 	  = models.CharField(max_length = 100)
	customer_abn 	  = models.CharField(max_length=100)
	customer_contact  = models.CharField(max_length = 50)
	customer_email 	  = models.EmailField(max_length=254)
	customer_address  = models.TextField()
	customer_number   = models.CharField(max_length = 200)
	customer_contact1 = models.CharField(max_length = 200)
	customer_address1 = models.TextField()
	customer_number1  = models.CharField(max_length = 200)
	is_vendor		  = models.BooleanField(default = False)

	def __str__(self):
		return self.customer_name



class WorkOrder(models.Model):
	customer 				= models.ForeignKey(Customer,on_delete=models.CASCADE)
	description 			= models.TextField()
	description_long_text 	= models.TextField()
	initial_deu_date 		= models.DateField(null=True,blank=True)
	quote 					= models.PositiveIntegerField()
	customer_contact_date 	= models.DateField()
	quote_sent_date 		= models.DateField()
	revision 				= models.PositiveIntegerField()
	promised_delivery_date  = models.DateField()
	created_by 				= models.ForeignKey(User,on_delete=models.CASCADE,related_name='created_by',null=True,blank=True)
	created_date 			= models.DateTimeField(auto_now = True,auto_now_add = False)
	modified_by 			= models.ForeignKey(User,on_delete=models.CASCADE,related_name='modified_by',null=True,blank=True)
	modified_date 			= models.DateTimeField(auto_now = False,auto_now_add = True)
	job_status 				= models.CharField(max_length=100, choices=JOB_STATUS, default="Quoting")
	all_tasks_complete 		= models.BooleanField(default = False)
	is_template 			= models.BooleanField(default = False)


	def __str__(self):
		return self.description



DOC_CAT = (
	("Cat 1","Cat 1"),
	("Cat 2","Cat 2"),
	("Cat 3","Cat 3"),
	("Cat 4","Cat 4"),
	)


class Documentation(models.Model):
	work_order = models.ForeignKey(WorkOrder,on_delete=models.CASCADE)
	category = models.CharField(max_length=100, choices=DOC_CAT)	
	document   = models.FileField(upload_to = "documentation")

	def __str__(self):
		return "%s"%(self.id)


class Employee(models.Model):
	user                           = models.OneToOneField(User,null=True,blank=True)
	external_system 			   = models.PositiveIntegerField()
	name  						   = models.CharField(max_length=100)
	start_date 					   = models.DateField()
	terminate_date 				   = models.DateField(null=True,blank=True)
	terminated 					   = models.BooleanField(default=False)
	photo 						   = models.ImageField(upload_to="employee")
	address 					   = models.TextField()
	phone_number 				   = models.CharField(max_length = 50)
	emergency_contact 			   = models.CharField(max_length = 50)
	emergency_contact_relationship = models.CharField(max_length = 50)
	emergency_contact_number 	   = models.CharField(max_length = 50)
	cost_rate 					   = models.FloatField()
	chargeout_rate 				   = models.FloatField()

	def __str__(self):
		return self.name


def terminated_receiver(sender, instance, *args, **kwargs):
	if instance.terminate_date:
		instance.terminated = True
	else:
		instance.terminated = False

pre_save.connect(terminated_receiver, sender=Employee)


class Task(models.Model):
	work_order 		 = models.ForeignKey(WorkOrder,on_delete=models.CASCADE)
	task_description = models.TextField()
	start_date       = models.DateField()
	end_date         = models.DateField()
	task_status 	 = models.CharField(max_length=100, choices=TASK_STATUS, default="In Progress")
	task_duration 	 = models.IntegerField(default=0)
	task_assigned_to = models.ManyToManyField(Employee)
	task_due_date 	 = models.DateField()

	def __str__(self):
		return self.task_description

def task_duration_receiver(sender, instance, *args, **kwargs):
    day_between = instance.end_date-instance.start_date
    passed_hour = day_between.days * 24 + day_between.seconds // 3600
    instance.task_duration = int(passed_hour)

pre_save.connect(task_duration_receiver, sender=Task)


class TimeCard(models.Model):
	work_order 	  = models.ForeignKey(WorkOrder,on_delete=models.CASCADE)
	employee_name = models.ForeignKey(Employee,on_delete=models.CASCADE)
	start_time 	  = models.DateTimeField()
	end_time      = models.DateTimeField()
	duration      = models.FloatField(default=0)
	approved      = models.BooleanField(default = False)
	approved_date = models.DateTimeField(null=True,blank=True)

	gst = models.FloatField(default=0)
	total_cost = models.FloatField(default=0)
	mp = models.FloatField(default=0)
	ma = models.FloatField(default=0)

	def __str__(self):
		return self.employee_name.name

	def get_total_ex_gst(self):
		duration = self.duration
		chargeout_rate = self.employee_name.chargeout_rate
		markup_percentage = self.mp
		markup_amount = self.ma
		line_total_ex_gst = duration * chargeout_rate * (1+markup_percentage/100) + markup_amount
		return line_total_ex_gst

class Purchase(models.Model):
	work_order 				= models.ForeignKey(WorkOrder,on_delete=models.CASCADE)
	po_status 			  	= models.CharField(max_length=100, choices=PO_STATUS, default="New")
	vendor					= models.ForeignKey(Customer,on_delete=models.CASCADE)
	po_cost 				= models.FloatField(default=0)
	ordered_date 		 	= models.DateField(auto_now = True,auto_now_add = False)
	required_date 		 	= models.DateField()
	promised_delivery_date	= models.DateField()
	approved 			  	= models.BooleanField(default=False)

	def __str__(self):
		return self.work_order.description




class Item(models.Model):
	purchase 	= models.ForeignKey(Purchase,on_delete=models.CASCADE)
	line_text = models.CharField(max_length=200)
	quantity = models.PositiveIntegerField(default=1)
	received_qty = models.PositiveIntegerField(default=1)
	received_date = models.DateField()
	po_cost_ex_gst = models.FloatField(default=0)
	gst = models.FloatField(default=0)
	line_cost 	= models.FloatField(default=0)
	approved = models.BooleanField(default=False)
	mp = models.FloatField(default=0)
	ma = models.FloatField(default=0)
	is_markuped = models.BooleanField(default=False)

	def __str__(self):
		return self.line_text

	def get_total_ex_gst(self):
		qty = self.quantity
		cost = self.po_cost_ex_gst
		markup_percentage = self.mp
		markup_amount = self.ma
		line_total_ex_gst = qty * cost * (1+markup_percentage/100) + markup_amount
		return line_total_ex_gst




class Invoice(models.Model):
	work_order						= models.OneToOneField(WorkOrder,on_delete=models.CASCADE)
	external_account_code 			= models.CharField(max_length=100,null=True, blank=True)
	invoice_date 					= models.DateField(null=True, blank=True)
	expected_payment_date 			= models.DateField(null=True, blank=True)
	invoice_status 					= models.CharField(max_length=100, choices=INVOICE_STATUS,null=True, blank=True)
	email_to 						= models.EmailField(max_length = 100,null=True, blank=True)
	description 					= models.TextField(null=True, blank=True)
	payment_details 				= models.TextField(null=True, blank=True)
	invoice_to 						= models.TextField(null=True, blank=True)
	invoice_from_org 				= models.TextField(null=True, blank=True)
	invoice_from 					= models.TextField(null=True, blank=True)
	invoice_customer 				= models.ForeignKey(Customer, on_delete=models.CASCADE, null=True, blank=True)
	invoice_customer_info 			= models.TextField(null=True, blank=True)
	is_created                      = models.BooleanField(default=False)
	send_copy_tick_box 				= models.BooleanField(default = False)
	add_pdf_attachment_tick_box 	= models.BooleanField(default = False)
	add_invoice_attachment_to_email = models.BooleanField(default = False)
	approved                        = models.BooleanField(default=False)
	
	def __str__(self):
		return self.work_order.description

to_form = '''
{}
{}
'''

def invoice_create_receiver(sender, instance, created, *args, **kwargs):
	if created:
		ito = to_form.format(instance.customer.customer_name, instance.customer.customer_address).strip()
		icf = to_form.format(instance.customer.customer_name, instance.customer.customer_email).strip()
		Invoice.objects.create(
			work_order = instance,
			email_to = instance.customer.customer_email,
			invoice_customer = instance.customer,
			invoice_to = ito,
			invoice_customer_info = icf
			)

post_save.connect(invoice_create_receiver, sender=WorkOrder)

def deu_date_receiver(sender, instance, *args, **kwargs):
	if instance.job_status == "Quoting" or instance.job_status == "New Job":
		pdd = instance.promised_delivery_date
		instance.initial_deu_date = pdd
pre_save.connect(deu_date_receiver, sender=WorkOrder)


class Preference(models.Model):
	user = models.OneToOneField(User)
	logo = models.ImageField(upload_to="invoice_logo", null=True,blank=True)
	address = models.TextField(null=True,blank=True)
	markup_percentage = models.FloatField(default=0)
	markup_amount = models.FloatField(default=0)

	def __str__(self):
		return self.user.username


def preference_receiver(sender,created, instance, *args, **kwargs):
	if created:
		Preference.objects.create(
			user = instance

src/templates/invoice/inv_table.html
        <div class="col-sm-12">
            <table class="table table-bordered table-sm">
              <thead>
                <tr>
                  <th>Description</th>
                  <th>Qty</th>
                  <th>Cost</th>
                  <th>Gst</th>
                  <th>Markup %</th>
                  <th>Markup $</th>
                  <th>Line Total Ex Gst</th>
                  <th>Line Total</th>
                </tr>
              </thead>
              <tbody>
                {% for item in items %}
                <tr id="item{{item.id}}">
                  <td>{{ item.line_text }}</td>
                  <td>{{ item.quantity }}</td>
                  <td>${{ item.po_cost_ex_gst|floatformat:2 }}</td>
                  <td>${{ item.gst|floatformat:2 }}</td>
                  <td><input data-url="/update/markup/percentage/{{ item.id }}/" id="mp" type="number" step="0.1" class="form-control" value="{{ item.mp }}" name="markup_p"></td>
                  <td><input data-url="/update/markup/amount/{{ item.id }}/" id="ma" type="number" step="0.1" class="form-control" value="{{ item.ma }}" name="markup_a"></td>
                  <td>${{ item.get_total_ex_gst|floatformat:2 }}</td>
                  <td>${{ item.line_cost|floatformat:2 }}</td>
                </tr>
                {% endfor %}
                <tr>
                  <td></td>
                  <td></td>
                  <td></td>
                  <td></td>
                  <td></td>
                  <td></td>
                  <td>ITEM TOTAL</td>
                  <td>${{ po_total_cost|floatformat:2 }}</td>
                </tr>

              </tbody>
            </table>
            <table class="table table-bordered table-sm">
              <thead>
                <tr>
                  <th>Time Card</th>
                  <th>Chargeout Rate</th>
                  <th>Duration</th>
                  <th>Gst</th>
                  <th>Markup %</th>
                  <th>Markup $</th>
                  <th>Line Total Ex Gst</th>
                  <th>Line Total</th>
                </tr>
              </thead>
              <tbody>
                {% for card in tmcs %}
                <tr id="tmcs{{item.id}}">
                  <td>{{ card.id }}</td>
                  <td>${{ card.employee_name.chargeout_rate|floatformat:2 }}</td>
                  <td>{{ card.duration|floatformat:2 }}</td>
                  <td>${{ card.gst|floatformat:2 }}</td>
                  <td><input data-url="/timecard/update/markup/percentage/{{ card.id }}/" id="tmp" type="number" step="0.1" class="form-control" value="{{ card.mp }}" name="markup_p"></td>
                  <td><input data-url="/timecard/update/markup/amount/{{ card.id }}/" id="tma" type="number" step="0.1" class="form-control" value="{{ card.ma }}" name="markup_a"></td>
                  <td>${{ card.get_total_ex_gst|floatformat:2 }}</td>
                  <td>${{ card.total_cost|floatformat:2 }}</td>
                </tr>
                {% endfor %}
                <tr>
                  <td></td>
                  <td></td>
                  <td></td>
                  <td></td>
                  <td></td>
                  <td></td>
                  <td>TIME CARD TOTAL</td>
                  <td>${{ time_total_cost|floatformat:2 }}</td>
                </tr>
                <tr style="background-color: #3e3e3eb3;">
                  <td></td>
                  <td></td>
                  <td></td>
                  <td></td>
                  <td></td>
                  <td></td>
                  <td>TOTAL</td>
                  <td>${{ total_final|floatformat:2 }}</td>
                </tr>

              </tbody>
            </table> 
        </div>
      

<script>
$("[id='mp']").bind('keyup change', function (e) {
    if (! $(this).data("previousValue") || 
           $(this).data("previousValue") != $(this).val()
       )
   {       
        $(this).data("previousValue", $(this).val());
   }

    var url = $(this).attr("data-url")
    var furl = url + $(this).val() + "/"
    console.log(furl)
    $.ajax({
      url: furl,
      type: 'get',
      dataType: 'json',
      success: function (data) {
        console.log(data.update_row)
        $("#inv_container").html("")
        $("#inv_container").html(data.update_row)
      }
    });
        
});

$("[id='ma']").bind('keyup change', function (e) {
    if (! $(this).data("previousValue") || 
           $(this).data("previousValue") != $(this).val()
       )
   {       
        $(this).data("previousValue", $(this).val());
   }

    var url = $(this).attr("data-url")
    var furl = url + $(this).val() + "/"
    console.log(furl)
    $.ajax({
      url: furl,
      type: 'get',
      dataType: 'json',
      success: function (data) {
        console.log(data.update_row)
        $("#inv_container").html("")
        $("#inv_container").html(data.update_row)
      }
    });
        
});

$("[id='tmp']").bind('keyup change', function (e) {
    if (! $(this).data("previousValue") || 
           $(this).data("previousValue") != $(this).val()
       )
   {       
        $(this).data("previousValue", $(this).val());
   }

    var url = $(this).attr("data-url")
    var furl = url + $(this).val() + "/"
    console.log(furl)
    console.log($(this).val())
    $.ajax({
      url: furl,
      type: 'get',
      dataType: 'json',
      success: function (data) {
        console.log(data.update_row)
        $("#inv_container").html("")
        $("#inv_container").html(data.update_row)
      }
    });
        
});

$("[id='tma']").bind('keyup change', function (e) {
    if (! $(this).data("previousValue") || 
           $(this).data("previousValue") != $(this).val()
       )
   {       
        $(this).data("previousValue", $(this).val());
   }

    var url = $(this).attr("data-url")
    var furl = url + $(this).val() + "/"
    console.log(furl)
    console.log($(this).val())
    $.ajax({
      url: furl,
      type: 'get',
      dataType: 'json',
      success: function (data) {
        console.log(data.update_row)
        $("#inv_container").html("")
        $("#inv_container").html(data.update_row)
      }
    });
        
});


</script>

src/templates/invoice/invoice_list.html
{% extends 'base.html' %}
{% load widget_tweaks %}


{% block content %}


		<div class="content-header">
			<div class="d-flex align-items-center">
				<div class="mr-auto">
					<h3 class="page-title">Invoice List</h3>
					<div class="d-inline-block align-items-center">
						<nav>
							<ol class="breadcrumb">
								<li class="breadcrumb-item"><a href="#"><i class="fa fa-home"></i></a></li>
								<li class="breadcrumb-item" aria-current="page">Invoice</li>
								<li class="breadcrumb-item active" aria-current="page">Invoice List
								</li>
							</ol>
						</nav>
					</div>
				</div>
				<div class="right-title">
				</div>
			</div>
		</div>


<section class="content">

		  <div class="row">
			<div class="col-xl-4 col-md-6 col-12 ">
				<div class="box box-inverse box-success">
				  <div class="box-body">
					<div class="flexbox">
					</div>

					<div class="text-center my-2">
					  <div class="font-size-60">{{ not_approved }}</div>
					  <span>Invoice Requiring Approval</span>
					</div>
				  </div>
				</div>
			</div>
			<!-- /.col -->
			<div class="col-xl-4 col-md-6 col-12 ">
				<div class="box box-inverse box-primary">
				  <div class="box-body">
					<div class="flexbox">
					</div>

					<div class="text-center my-2">
					  <div class="font-size-60">{{ inv_not_sent }}</div>
					  <span>PO Invoice not sent but approved</span>
					</div>
				  </div>				
				</div>
			</div>
			<!-- /.col -->

			<div class="col-xl-4 col-md-6 col-12">
				<div class="box box-inverse box-danger">
				  <div class="box-body">
					<div class="flexbox">
					</div>

					<div class="text-center my-2">
					  <div class="font-size-60">0</div>
					  <span>Invoices where the Costs <= Job Costs</span>
					</div>
				  </div>

				</div>
			</div>
			<!-- /.col -->
<!-- 			<div class="col-xl-3 col-md-6 col-12">
				<div class="box box-inverse box-warning">
				  <div class="box-body">
					<div class="flexbox">
					  <h5>Pending Invoice</h5>
					</div>

					<div class="text-center my-2">
					  <div class="font-size-60">00</div>
					  <span>Pending</span>
					</div>
				  </div>
				</div>
			</div> -->
			<!-- /.col -->

		  </div>	

		  <div class="row">
				<div class="col-12">
					<div class="box">
						<div class="box-header with-border">		
							<h4 class="box-title">Invoice List</h4>
							<h6 class="box-subtitle">Export Invoice List to Copy, CSV, Excel, PDF & Print</h6>
						</div>
						<div class="box-body">						
							<div class="table-responsive">
								
								<table id="example" class="table table-lg invoice-archive">
									<thead>
										<tr>
											<th>#ID</th>
											<th>Invoice Work Order</th>
											<th>Invoice Date</th>
											<th>Invoice Status</th>
											<th>Expected Payment Date</th>
											<th>Invoice Customer</th>
											<th>Approved?</th>
											<th class="text-center">Actions</th>
										</tr>
									</thead>
									<tbody>

									{% for invoice in invoice_list %}
										<tr>
											<td>#{{ invoice.id }}</td>
											<td>{{ invoice.work_order }}</td>
											<td>{{ invoice.invoice_date|date:"D d/m/y" }}</td>
											<td>{{ invoice.invoice_status }}</td>
											<td>{{ invoice.expected_payment_date|date:"D d/m/y" }}</td>
											<td>{{ invoice.invoice_customer }} </td>
											<td>{{ invoice.approved }} </td>
											<td class="text-center">
												<div class="list-icons d-inline-flex">
													<div class="list-icons-item dropdown">
														<a href="#" class="list-icons-item dropdown-toggle" data-toggle="dropdown"><i class="fa fa-file-text"></i></a>
														<div class="dropdown-menu dropdown-menu-right">
															<a href="#" id="invoice_edit" data-url="{% url 'invoice_update' invoice.id %}" class="dropdown-item"><i class="fa fa-pencil" ></i> Edit</a>
															<a href="{% url 'invoice_paid' invoice.id %}" data-url="{% url 'invoice_update' invoice.id %}" class="dropdown-item"><i class="fa fa-money" ></i> Paid</a>
															<a href="{% url 'invoice_sent' invoice.id %}"  data-url="{% url 'invoice_update' invoice.id %}" class="dropdown-item"><i class="fa fa-file" ></i> Sent</a>
															<a href="{% url 'invoice_approved' invoice.id %}" class="dropdown-item"><i class="mdi mdi-check"></i>Approved</a>

														</div>
													</div>
												</div>
											</td>
										</tr>

										{% endfor %}



									</tbody>
								</table>
																
							</div>
						</div>
					</div>
				</div>
			</div>
		  <!-- /.row -->

		</section>


<div id="editcontainer"></div>


{% endblock %}

src/templates/invoice/update_invoice.html
{% load widget_tweaks %}
<div class="modal fade" id="updateModal">
    <div class="modal-dialog modal-lg">
      <div class="modal-content">
      
        <!-- Modal Header -->
        <div class="modal-header">
          <h4 class="modal-title">Create Invoice</h4>
          <button type="button" class="close" data-dismiss="modal">&times;</button>
        </div>
        
        <!-- Modal body -->
        <div class="modal-body">
              <div class="form-group">


      <form action="{% url 'invoice_update' form.instance.id %}" method="POST" enctype="multipart/form-data">{% csrf_token %}

      <div class="row">
        <div class="col-sm-6">
          {% if form.instance.invoice_from_org %}
          {% render_field form.invoice_from_org class="form-control" rows="2" %}
          {% else %}
            <textarea name="invoice_from_org" cols="40" rows="2" class="form-control" id="id_invoice_from_org">{{ inv_form }}</textarea>
          {% endif %}
          
        </div>
        <div class="col-sm-5">
          <img src="{{ request.user.preference.logo.url }}" style="width: 30%;" class="pull-right">
        </div>
        <div class="col-sm-12" style="font-size: 20px;">
          <p><center><b>Invoice</b></center></p>
        </div>
        <div class="col-sm-6">
          <div class="row">
            <div class="col-sm-2">
              <label>To</label>
            </div>
            <div class="col-sm-10">
              {% render_field form.invoice_to class="form-control" rows="2" %}
            </div>
          </div>      
          <div class="row top10">
            <div class="col-sm-2">
              <label>From</label>
            </div>
            <div class="col-sm-10">
            {% if form.instance.invoice_from %}
            {% render_field form.invoice_from class="form-control" rows="2" %}
            {% else %}
              <textarea name="invoice_from" cols="40" rows="2" class="form-control" id="id_invoice_from">{{ inv_form }}</textarea>
            {% endif %}
            </div>
          </div>     
        </div>
        <div class="col-sm-6 col-sm-offset-1">
          <div class="row">
            <div class="col-sm-3">
              <label>Invoice</label>
            </div>
            <div class="col-sm-9">
              <label>#{{ form.instance.id }}</label>
            </div>
          </div>  
          <div class="row">
            <div class="col-sm-3">
              <label>Issue Date</label>
            </div>
            <div class="col-sm-9">
              {% render_field form.invoice_date class="form-control" %}
            </div>
          </div> 
          <div class="row top10">
            <div class="col-sm-3">
              <label>Customer</label>
            </div>
            <div class="col-sm-9">
              {% render_field form.invoice_customer_info class="form-control" rows="2" %}
            </div>
          </div>  
        </div>
      </div>
      <div class="row top10" id="inv_container">
      {% include 'invoice/inv_table.html' %}
      </div>

        


              <p class="top10">
                <button type="submit" class="btn btn-primary pull-right">Save</button>
                <button type="button" class="btn btn-danger pull-right right10" data-dismiss="modal">Close</button>
              </p>

      </form>

    </div>
        </div>
        
        
      </div>
    </div>
  </div>